#!/bin/bash

tput setaf 5
cat << splash

          :::     :::::::::  ::::    ::: ::::::::::: :::    ::: 
       :+: :+:   :+:    :+: :+:+:   :+:     :+:     :+:    :+:  
     +:+   +:+  +:+    +:+ :+:+:+  +:+     +:+      +:+  +:+    
   +#++:++#++: +#++:++#:  +#+ +:+ +#+     +#+       +#++:+      
  +#+     +#+ +#+    +#+ +#+  +#+#+#     +#+      +#+  +#+      
 #+#     #+# #+#    #+# #+#   #+#+#     #+#     #+#    #+#      
###     ### ###    ### ###    #### ########### ###    ###

            Arch Linux with generations to come

splash
tput sgr0

_option() {
    tput setaf 5
    echo -n 'arnixctl '
    tput bold
    echo -ne "$1"
    tput sgr0
    echo -n ' - '
    tput bold
    echo "$2"
    tput sgr0
}

case $1 in
    *)
        _option 'help' 'this menu'
        _option 'update' "update Arnix's files"
        _option 'rollback' 'switch to a previous generation'
        _option 'uninstall' 'revert hijack'
    ;;
    update)
        # Requirement: Reliable (has fallback)
    ;;
    rollback)
        # Requirement: User can select generation
    ;;
    uninstall)
        # Requirement: User can select generation
    ;;
esac